export const columns = [
    { value: 'fiscalPeriod', width: 120, caption: 'Fiscal Period'},
    { value: 'quarter', width: 80, caption: 'Quarter'},
    { value: 'month', width: 150, caption: 'Month'},
    { value: 'channelName', width: 150, caption: 'Channel Name'},
    { value: 'subChannelName', width: 150, caption: 'Sub Channel Name'},
    { value: 'depotName', width: 200, caption: 'Depot Name'},
    { value: 'businessStateName', width: 200, caption: 'Business State Name'},
    { value: 'stateName', width: 200, caption: 'State Name'},
    { value: 'districtName', width: 200, caption: 'District Name'},
    { value: 'talukName', width: 200, caption: 'Taluk'},
    { value: 'placeName', width: 200, caption: 'Place Name'},
    { value: 'pincode', width: 250, caption:'Distributor Pincode'},
    { value: 'nameOfFirm', width: 200, caption: 'Name of Firm'},
    { value: 'rmsCode', width: 100, caption: 'RMS Code'},
    { value: 'shipToPt', width: 200, caption: 'SAP Customer Code'},
    { value: 'billDoc', width: 120, caption: 'Invoice Number'},
    { value: 'cancelInvoiceNo', width: 200, caption: 'Cancel Invoice Number'},
    { value: 'invoiceType', width: 120, caption: 'Invoice Type'},
    { value: 'productCode', width: 150, caption: 'Product Code'},
    { value: 'sapMaterialCode', width: 150, caption: 'SAP Material Code'},
    { value: 'productName', width: 200, caption: 'Product Name'},
    { value: 'segmentName', width: 150, caption: 'Category'},
    { value: 'subSegmentName', width: 180, caption: 'Sub Category'},
    { value: 'brandName', width: 150, caption: 'Brand Name'},
    { value: 'subBrandName', width: 150, caption: 'Variant'},
    { value: 'baseUom', width: 100, caption: 'UOM'},
    { value: 'netValue', width: 100, caption: 'Net Value'},
    { value: 'mrp', width: 70, caption: 'MRP'},
    { value: 'mrpSlab', width: 120, caption: 'MRP Slab'},
    { value: 'basicPrice', width: 120, caption: 'Basic Price'},
    { value: 'qty', width: 100, caption: 'Bill Quantity'},
    { value: 'gto', width: 80, caption: 'GTO'},
    { value: 'cdTdSrd', width: 200, caption: 'CDTDSRD'},
    { value: 'cd', width: 200, caption: 'CD'},
    { value: 'td', width: 200, caption: 'TD'},
    { value: 'tto', width: 80, caption: 'TTO'},
    { value: 'rdd', width: 200, caption: 'RDD'},
    { value: 'spd', width: 200, caption: 'SPD'},
    { value: 'srd', width: 200, caption: 'SRD'},
    { value: 'taxAmount', width: 200, caption: 'Tax Amount'},
    { value: 'sgst', width: 200, caption: 'SGST'},
    { value: 'cgst', width: 200, caption: 'CGST'},
    { value: 'igst', width: 200, caption: 'IGST'},
    { value: 'pricingProcedure', width: 200, caption: 'Pricing Procedure Name'},
    { value: 'customerReference', width: 200, caption: 'Customer Reference'},
    { value: 'sapCode', width: 100, caption: 'SAP Code'},
    { value: 'meName', width: 200, caption: 'ME Name'},
    { value: 'rsmName', width: 200, caption: 'RSM Name'},
    { value: 'asmName', width: 200, caption: 'ASM Name'},
    { value: 'aseName', width: 200, caption: 'ASE Name'},
    { value: 'soName', width: 200, caption: 'SO Name'},
    { value: 'srName', width: 200, caption: 'SR Name'},
    { value: 'replaceProductCode', width: 200, caption: 'Replaced Product'},
    { value: 'consumerPromo', width: 200, caption: 'Consumer Promo'},
    { value: 'productType', width: 200, caption: 'Product Type'},
    { value: 'barcode', width: 200, caption: 'Barcode'},
    { value: 'hsnNumber', width: 200, caption: 'HSN Number'},
    { value: 'productCategory', width: 150, caption: 'Custom Category'}
];