export const reportData = [{
    channelName: "Channel 1",
    subChannelName: "Sub Channel 4",
    businessStateName: "UTTAR PRADESH",
    stateName: "UTTAR PRADESH",
    districtName: "HARDOI",
    placeName: "PIPRI",
    depotName: "LUCKNOW",
    aseName: "Rocky",
    meName: "Garuda",
    mrp: 15,
    mrpSlab: "15 to 19",
    segmentName: "Segment 2",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "December",
    invoiceType: "Sales",
    qty: 74,
    gto: 72035.2,
    tto: 81971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Baba",
    meName: "Guru",
    mrp: 15,
    mrpSlab: "15 to 19",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 214,
    gto: 212035.2,
    tto: 211971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  },
  {
    channelName: "Channel 1",
    subChannelName: "Sub Channel 5",
    businessStateName: "MADHYA PRADESH",
    stateName: "MADHYA PRADESH",
    districtName: "BHOPAL",
    placeName: "BHOPAL",
    depotName: "BHOPAL",
    aseName: "Samba",
    meName: "Gabbar",
    mrp: 55,
    mrpSlab: "50 to 99",
    segmentName: "Segment 1",
    subSegmentName: "Sub Segment 2",
    fiscalPeriod: "2023-2024",
    quarter: "Q4",
    month: "November",
    invoiceType: "Sales",
    qty: 24,
    gto: 2035.2,
    tto: 1971.17
  }
];